### PR TITLE
make browser_cookie3 work with Chromium v80, not just Chrome v80

### LINKED ISSUE #55: chrome failed
Version 80.0.3987.122 (Official Build) (64-bit)

> 
In [32]: cj = browser_cookie3.chrome()
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-32-664d28acebc7> in <module>
----> 1 cj = browser_cookie3.chrome()

/mnt/os/opt/anaconda3/lib/python3.7/site-packages/browser_cookie3/__init__.py in chrome(cookie_file, domain_name)
    463     domain name to only load cookies from the specified domain
    464     """
--> 465     return Chrome(cookie_file, domain_name).load()
    466 
    467 

/mnt/os/opt/anaconda3/lib/python3.7/site-packages/browser_cookie3/__init__.py in load(self)
    267                     expires = expires.timestamp()
    268 
--> 269             value = self._decrypt(item[5], item[6])
    270             c = create_cookie(host, path, secure, expires, name, value)
    271             cj.set_cookie(c)

/mnt/os/opt/anaconda3/lib/python3.7/site-packages/browser_cookie3/__init__.py in _decrypt(self, value, encrypted_value)
    320         decrypted = cipher.feed(encrypted_value[:encrypted_value_half_len])
    321         decrypted += cipher.feed(encrypted_value[encrypted_value_half_len:])
--> 322         decrypted += cipher.feed()
    323         return decrypted.decode("utf-8")
    324 

/mnt/os/opt/anaconda3/lib/python3.7/site-packages/pyaes/blockfeeder.py in feed(self, data)
    167         # Finalize; process the spare bytes we were keeping
    168         if data is None:
--> 169             result = self._final(self._buffer, self._padding)
    170             self._buffer = None
    171             return result

/mnt/os/opt/anaconda3/lib/python3.7/site-packages/pyaes/blockfeeder.py in _block_final_decrypt(self, data, padding)
     75 def _block_final_decrypt(self, data, padding = PADDING_DEFAULT):
     76     if padding == PADDING_DEFAULT:
---> 77         return strip_PKCS7_padding(self.decrypt(data))
     78 
     79     if padding == PADDING_NONE:

/mnt/os/opt/anaconda3/lib/python3.7/site-packages/pyaes/util.py in strip_PKCS7_padding(data)
     56 
     57     if pad > 16:
---> 58         raise ValueError("invalid padding byte")
     59 
     60     return data[:-pad]

ValueError: invalid padding byte

### PR DESCRIPTION
**Pull request by dlenski**
It appears that they are 100% identical, except for the name of the keyring where the password is stored.

Should close #55.

### CODE REVIEW

**Comment by borisbabic** [comment]
I would prefer it if Chrome was the choice if both are present since that's what it uses now. It's better not to break it for people who upgrade and currently have both.

**Comment by dlenski** [comment]
> I would prefer it if Chrome was the choice if both are present since that's what it uses now. It's better not to break it for people who upgrade and currently have both.

Good point. Fixed in 6cb09218c420b1432b5da7cbd14668c08e7ad44e, so that it will try Chrome first.

**Comment by dlenski** [comment]
Any thoughts on the updated PR, @borisbabic ?

**Comment by borisbabic** [comment]
I was concerned about https://github.com/borisbabic/browser_cookie3/issues/55#issuecomment-699832449 but I can still merge this, thanks for your contribution!

**Comment by dlenski** [comment]
Awesome. Thank you! We really need more details to figure out what's going on it that commenter's case…

**Pull request merged**
