### PR TITLE
Fixes case where the APPDATA env variable is a mapped

### PR DESCRIPTION
**Pull request by mrmups**
The APPDATA Environment variable is sometimes mapped in AD environments. This breaks the current implementation which uses '..\Local\' to ensure that the local appdata directory is being used. This change uses the LOCALAPPDATA Environment variable, which is always mapped to the '*\AppData\Local' path.

### CODE REVIEW

**Comment by borisbabic** [comment]
I'm more of a linux guy, is there some issue with leaving `..\Local` as an option? I'd rather not break stuff for people, even if they may have a weird setup.

**Comment by mrmups** [comment]
The issue with leaving `..\Local` is it's assuming that the `*\AppData\Local` path exists. In the case of roaming profiles with folder redirection, this is not the case.
Typically the AppData directory will contain three folders, `Local`, `LocalLow` and `Roaming`. 
Roaming profiles with folder redirection means that certain directories will exist on a network share instead of the local computer. Of the three AppData directories, only the `Roaming` directory is the only directory that is redirected. 

This means the APPDATA Environment variable is changed to point to the network share instead of the directory on the local computer. This means it would look something like this:
`\\fileserver1.example.com\Users$\mrmups\AppData\Roaming`
If we left the `..\Local` option, then the it would attempt to get the cookie files form `\\fileserver1.example.com\Users$\mrmups\AppData\Local`, which isn't a valid path.

Since the `cookie_file` declaration stops as soon as one of the conditions returns a value that isn't `None`, we can only specify one path using the `os.path.join()` method, because that will always return a path even if it doesn't exist.

Alternatively, we can check if the path exists before assigning it to the `cookie_file` variable with something like this:

```
cookie_file = cookie_file or windows_group_policy_path()
if not cookie_file:
    cookie_path = 'Google\\Chrome\\User Data\\Default\\Cookies'
    if os.path.exists(os.path.join(os.getenv('LOCALAPPDATA', ''), cookie_path )):
        cookie_file = os.path.join(os.getenv('LOCALAPPDATA', ''), cookie_path )
    elif os.path.exists(os.path.join(os.getenv('APPDATA', ''), cookie_path )):
        cookie_file = os.path.join(os.getenv('APPDATA', ''), cookie_path )
    elif os.path.exists(os.path.join(os.getenv('APPDATA', ''), '..\Local\\' + cookie_path)):
        cookie_file = os.path.join(os.getenv('APPDATA', ''), '..\Local\\' + cookie_path )
```

I'm realizing now that [1938f90](https://github.com/borisbabic/browser_cookie3/pull/17/commits/1938f9070f2b0eae7bfd233064af98cbbc82f42c) has some issues with the filepaths anyway (leading \\ will break the path), so that commit should be skipped. I'll submit another PR with either just the LOCALAPPDATA Environment variable or the path validation checks mentioned above if you're interested.

**Comment by borisbabic** [comment]
I may have been unclear, I was questioning why the current path was removed as option not the introduction of new possible paths. I am of course open to accepting new possible paths that are checked _after_ the current path, however I'd need convincing to remove the current check or to check some other path before the current one. 

You don't need to submit a new PR, you can update the current one.

**Comment by mrmups** [comment]
I removed the current path because it seemed redundant to the `os.getenv('LOCALAPPDATA', '')` method. I added it back in commit [33ee3d3](https://github.com/borisbabic/browser_cookie3/pull/17/commits/33ee3d3f8819dbfe35b09cbfc8a4181a04bf910d). Also since glob returns nothing if the path doesn't exist, I just used that method for chrome paths.

**Comment by borisbabic** [comment]
I'm not familiar enough with windows to know if people can have some weird setup where it isn't redundant. If it doesn't hurt I'd just leave it in there.

0.7.0 has been released to pypi.

**Pull request merged**
