### PR TITLE
Add new Chrome cookies path

### PR DESCRIPTION
**Pull request by mlojewski-me**

### CODE REVIEW

**Comment by borisbabic** [comment]
Did the same change happen for Chromium?

**Comment by mlojewski-me** [comment]
Yes I did, so I also updated Chromium cookie path

**Comment by jonscape** [comment]
Looks like it is also changing in Edge.

**Comment by rafiibrahim8** [comment]
@mlojewski-me Looks like the path has been changed for all Chromium-based browsers. Can you add them to the PR too? Also, it would be nice if you can keep the legacy paths just in case.

**Comment by rafiibrahim8** [comment]
This issue has been resolved in cd5d9710b9c8dd1a222d1754106be6dcaceb68dc (version [0.14.1](https://pypi.org/project/browser-cookie3/0.14.1/)).
Thank you

**Pull request closed without merging**
