### PR TITLE
Support non-default profiles in chrome

### PR DESCRIPTION
**Pull request by njw1204**
The current code read a cookie file from `<user_data_dir>/Default/Cookies`. but if the active profile name is not "Default", the cookie file exists under a different directory. so it will return wrong result (like an empty cookie jar). I was in trouble because of that, and finally found the solution.

Actually, it is under `<user_data_dir>/<profile_name>/Cookies`. "Default" is just a default profile name. so if the active profile name is "Profile 1", it is under `<user_data_dir>/Profile 1/Cookies`. The active profile can change in various situations, like [creating multiple profiles](https://pureinfotech.com/add-new-user-profiles-google-chrome/).

image
image

This patch will add extracting of active chrome profile name from 'Local State' file, and load a cookie from the correct directory. so it supports any non default chrome profiles.

image

Tested on Ubuntu 18.04 (Chrome 74.0) & Windows 10 (Chrome 74.0)

### CODE REVIEW

**Comment by borisbabic** [comment]
While I probably would have rather had it be this way from the start, I'm a bit wary when it comes to making backwards incompatible changes.

I would prefer it if this new behavior would be the fallback to the old behavior instead of the other way around, ie. I'd prefer that people who update the lib and don't change their code have the this lib first check `Default/Cookies` and then check `$activeProfile/Cookies`.

**Comment by borisbabic** [comment]
However, it would be good to be able to write software that just checks the active profile _first_ without prompting end user. If that's what you want then that should be opt in.

If not then you can just do the change from my previous comment and I'll create another issue for that.

Oh, and thanks for bringing my attention to this, it's a useful addition :+1:

**Comment by ele3131** [comment]
Make something like: chrome(domain_name=' xyz', profile=all) return a list of each profile cookies would be awesome, profile could be an optional argument (default behavior is get only Chrome's Default Profile).

**Comment by wimglenn** [comment]
FWIW the original project does search non-default profiles:  https://github.com/richardpenman/browsercookie/blob/e530d758ca47bed04138ed8d788f634f3f433c46/__init__.py#L105 
But it's missing many of the improvements that browser-cookie3 has ...

**Pull request closed without merging**
