### PR TITLE
Use pycryptodomex instead of pycryptodome

### LINKED ISSUE #77: Use pycryptodomex instead of pycryptodome
pycryptodome is to be used in place of PyCrypto and is to be used only in a virtualenv.

PyCrypto and pycryptodomex can coexist but pycryptodome and pycrypto cannot.

https://stackoverflow.com/a/48175912/7732434

Also:

Docstrings should use triple double quotes not tripple single quotes. You could also put the docstrings of some functions on one line instead of two.

Line https://github.com/borisbabic/browser_cookie3/blob/master/__init__.py#L221has an extra line.

### PR DESCRIPTION
**Pull request by elibroftw**
Closes  #77

### CODE REVIEW

**Comment by elibroftw** [comment]
Can the `pyaes` code be removed?

**Comment by rafiibrahim8** [comment]
Hey @elibroftw,
Can you replace `pyaes` with `Cryptodome.Cipher.AES` too?

**Comment by elibroftw** [comment]
I'm not on Linux so this needs to be tested before merging

**Comment by rafiibrahim8** [comment]
@elibroftw I can do that.

**Comment by rafiibrahim8** [comment]
@elibroftw,
Version [0.16.3](https://pypi.org/project/browser-cookie3/0.16.3/) has been released with these changes. Thank you for your contribution. :purple_heart:

**Pull request merged**
